create schema if not exists sistema_bancario;
use sistema_bancario;

create table CLIENTES(
NRO_CLIENTE INT NOT NULL,
DNI INT NOT NULL,
NOMBRE_APELLIDO VARCHAR(45) NOT NULL,
TELEFONO INT NOT NULL,
EMAIL VARCHAR(30),
DOMICILIO VARCHAR(45),
PRIMARY KEY (DNI)
);

create table CUENTAS(
NRO_CUENTA INT NOT NULL,
TIPO_CUENTA CHAR(20) NOT NULL, -- CA, CC
SALDO DOUBLE NOT NULL,
CBU INT NOT NULL,
TIPO_MONEDA VARCHAR(10) NOT NULL, -- PESO, DOLLAR
DNI_CLIENTE INT NOT NULL,
PRIMARY KEY (CBU),
CONSTRAINT fk_NRO_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI));